add automatic log removal function
CMSSNU/SKFlatAnalyzer pull request #148
Opened 2023-12-29 03:36 UTC by sihyunjeon

checks log directory and removes logs that are too old automatically

safety trigger set to 3days as some jobs might be submitted 12.29 night and still runs in 12.30 or 12.31.

if it's set to -1 , it won't remove anything automatically

2023-12-30 12:33 UTC, sansan9401 requested changes

2023-12-30 12:33 UTC, sansan9401 commented on python/PrintOldLogs.py
> +LogRemoval = int(UserInfo['LogRemoval'])
Could you add some code to handle the case when there is no 'LogRemoval' in UserInfo file to increase compatibility with existing UserInfo files?
For example,
```python
if 'LogRemoval' not in UserInfo:
    LogRemoval=-1 # or a large value?
else:
    LogRemoval = int(UserInfo['LogRemoval'])
```

2024-01-01 14:13 UTC, sihyunjeon commented
added try except in case someone writes `"-1"` instead of `-1` in the user info file

2024-01-02 08:46 UTC, sansan9401 approved these changes

2024-01-02 08:46 UTC, merged